### ISSUE TITLE
partial matching may be required after refactoring of readSource("BP")

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrremind#148]
Hi Falk,
I'm getting an error in the remind input data preparation that seem to come from the refactoring of `readSource("BP")` (line 65 throws the error)
https://github.com/pik-piam/mrremind/blob/a9dcd917a1362b94495e5487c043e715a39213b0/R/convertRogelj2017.R#L60-L68
In this case ` hist_gen_nuclear[k,2015,"Nuclear", pmatch = TRUE]` seems to solve the problem but I'm not sure if this is what was intended. Could you check this please? and also maybe the other calls to readSource("BP") which may have been affected?
Thanks!

**Comment by fbenke-pik** [comment]
Opened PR #149 to address this. I found other instances where this most likely will happen, and will address them in a separate fix.
