### ISSUE TITLE
Could use calcOutput("GDPpc") directly

### ISSUE THREAD

**Issue by johanneskoch94** [pik-piam/mrremind#164]
Not urgent, but since this a TODO, you may want to refactor this code at the same time. 
https://github.com/pik-piam/mrremind/blob/6e36496b3f64cf535a0aa20de89ab654c31d5c56/R/convertINNOPATHS.R#L7-L12
Instead of calling calcOutput("GDP") and then dividing by calcOutput("Population"), you can directly call calcOutput("GDPpc"). 
This will also make sure that the names are not messed up, as is (I'm almost certain) the case in the above division. I'm not sure if/where you fix this, but in any case, calling calcOutput("GDPpc") would make this a bit cleaner :)

**Comment by fbenke-pik** [comment]
See PR #171
