### ISSUE TITLE
convertIEA_WEO_2021() disregards the majority of global population

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#265]
https://github.com/pik-piam/mrremind/blob/5f68c0282d40bdece590d6418a85eb5e834ec656/R/convertIEA_WEO_2021.R#L10
`calcPE()` → `calcIO()` → `readIEA()` → IEA 2014 Energy Balances.

While there is some 2016 data in the updated 2014 balances, these are not complete.  Using 2016 as a base year for disaggregation
https://github.com/pik-piam/mrremind/blob/5f68c0282d40bdece590d6418a85eb5e834ec656/R/convertIEA_WEO_2021.R#L25
https://github.com/pik-piam/mrremind/blob/5f68c0282d40bdece590d6418a85eb5e834ec656/R/convertIEA_WEO_2021.R#L49
omits 83 % of world population, or 60 % of world PE demand.

**Comment by fbenke-pik** [comment]
Thanks for pointing that out! I have used this reference for disaggregation in other sources as well (e.g. BP). 

@0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q @LaviniaBaumstark 
What would be a reasonable reference for disaggregation? Just use 2014 from IEA Energy Balances, or another source altogether?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I used 2014 data as a local work-around for now.
We might want to put the last "valid" year of this source into some kind of variable, since it might change in the not-too-distant future :crossed_fingers:.
