### ISSUE TITLE
824cd74 misses some files

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#340]
https://github.com/pik-piam/mrremind/blob/3cb0168dd24b8eb5819be288f8348044751445fe/R/readIEA_WEO_2021.R#L14

```
~~~ Run readSource(type = "IEA_WEO_2021", subtype = "region")
~~~~ WARNING: 
~~~~ cannot open file 'WEO2021_Free_Data_Regions.csv': No such file or directory
~~~~ ERROR: cannot open the connection
Error in `file()`:
! cannot open the connection
```

**Comment by fbenke-pik** [comment]
Should be fixed

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Fails somewhere else now ;)
Thanks.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Fails somewhere else now ;) 

… when run on the cluster.

Soft links don't work for mounted directories, so debugging remotely is still impossible.

**Comment by fbenke-pik** [comment]
Soft links have been replaced by the real deal
