### ISSUE TITLE
EDGE_SSP1/EDGE_SSP2 return Inf FE|Industry|Solids for NEU

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#367]
which apparently spreads to `FE|Industry` and `FE`, as well as `World`.
```
$ tar -xOf /p/projects/rd3mod/inputdata/output/rev6.333_62eff8f7_validationremind.tgz ./historical.mif | \
    sed -n '1p; /Inf/ p' | \
    column -ts ';' | \
    less -S
```
Not sure whether `EDGE_SSP1` and `EDGE_SSP2` are relevant for anything, though.

**Comment by fbenke-pik** [comment]
Seems to be a Problem in `calcFEdemand` for Iceland

```
data <- calcOutput("FEdemand", subtype = "FE", aggregate = FALSE)
data["ISL",2025,"fesoi", pmatch=T]
```

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
So `EDGE_SSP1` and `EDGE_SSP2` are actually the outdated `industry/fixed_shares` calibration data we know to be false?  Why not just delete them?

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
Also, the problem is that `readEDGE('FE_stationary')` returns 0 `feindsolid` for `ISL` in `2020` [here](https://github.com/pik-piam/mrremind/blob/master/R/calcFEdemand.R#L351):
```
> stationary <- readSource("EDGE", subtype = "FE_stationary")
Run readSource(type = "EDGE", subtype = "FE_stationary")
~  - loading cache convertEDGE-F0bc1a876-816e8565.rds
Exit readSource(type = "EDGE", subtype = "FE_stationary") in 46.3 seconds
> stationary['ISL',c(2015, 2020, 2025),'SSP1.feindsolid']
An object of class "magpie"
, , scenario.item = SSP1.feindsolid

      year
region      y2015 y2020        y2025
   ISL 0.00460468     0 0.0005815233
```

**Comment by fbenke-pik** [comment]
I don't mind removing this, if you know for sure the data is known to be false. 

`reposearch EDGE_projections` suggests that 
'calcOutput("FE", source = "EDGE_projections", scenario_proj = "SSP1|SSP2")`  is only used to add the data to historical.mif. 

So if there are no objections by @LaviniaBaumstark i will remove this (Anastasis and Aman have added this a long time ago).

**Comment by LaviniaBaumstark** [comment]
o.k., remove it if it is only needed for validation and no one cares
