### ISSUE TITLE
calcCapital() results differ between 1242136 and 298465a, and nobody knows why

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#385]
Originates from remindmodel/remind#1276.

`calcCapital()` 
- loads capital stock data from PWT 
- turns it into a capital intensity with GDP data from PWT,
- then uses GDP data from the SSPs to calculate capital stocks again
- (plus some convergence stuff that is inconsequential to this)

https://github.com/pik-piam/mrremind/blob/8261c7f17bf31f5d602fe19f6f9233bc8634c411/R/calcCapital.R#L21-L28

```
> dimSums(capital[iso3c_EUR,c(2005, 2010),], 1, TRUE) * millionDol2trillionDol
An object of class "magpie"
, , variable = kap

      year
d1        y2005    y2010
  [1,] 40.96891 45.89958
```

```
gdpppp_hist_PWT <- gdpppp_hist
```
https://github.com/pik-piam/mrremind/blob/8261c7f17bf31f5d602fe19f6f9233bc8634c411/R/calcCapital.R#L32

```
dimSums(cap_intensity[iso3c_EUR,c(2005, 2010),] * gdpppp_hist_PWT[iso3c_EUR,c(2005, 2010),], 1, TRUE) * millionDol2trillionDol
An object of class "magpie"
, , variable.variable1 = kap.gdp in constant 2005 Int$PPP

      year
d1        y2005    y2010
  [1,] 40.96891 45.89958

dimSums(cap_intensity[iso3c_EUR,c(2005, 2010),] * gdpppp_hist[iso3c_EUR,c(2005, 2010),], 1, TRUE) * millionDol2trillionDol
An object of class "magpie"
, , variable.variable1 = kap.gdp in constant 2005 Int$PPP

      year
d1        y2005    y2010
  [1,] 59.22392 66.42289
```

So it appears that 1242136 and 298465a used different "`gdpppp_hist`" for transforming capital intensities back into capital stocks.  That, however, is not due to a change in `calcCapital()` [in that timeframe](https://github.com/pik-piam/mrremind/blame/298465a/R/calcCapital.R).

`mrdrivers` moved from 0.6.6 (pik-piam/mrdrivers#49) to 0.7.2 (pik-piam/mrdrivers#54) in the meantime, so maybe answers lie that way.

**Comment by orichters** [comment]
My suspicion:
- [this PR](https://github.com/pik-piam/mrdrivers/pull/54/files#diff-b3e3c2f6c72d9da4a0f437bfe33c1ad903696686b85eb7769ae871d68840e563) adds to `calcInternalGDPPastPWT()` the following line:
```
data <- GDPuc::convertGDP(data, "constant 2017 Int$PPP", unit, replace_NAs = c("linear", "no_conversion"))
```
PENN World Table data is read from [this file](https://github.com/johanneskoch94/mrdrivers/blob/471d12731b4b7b30485e86cb3f4b616a7c1854e8/R/readPWT.R#L8) called `/p/projects/rd3mod/inputdata/sources/PWT/pwt80.xlsx`, which states:

`rgdpna`: Real GDP at constant 2005 national prices (in mil. 2005US$)

So I don't think this data should be converted from 2017 to 2005 data. The PR does not show an explanation why this is the case, so I would rather revert this change.

**Comment by mleimbach** [comment]
Oliver, with conversion, GDP in 2005US$ becomes lower. I am still confused why we than see higher capital stocks (assuming that we apply the same capital intensity factors).

**Comment by orichters** [comment]
[This line](https://github.com/pik-piam/mrremind/blob/8261c7f17bf31f5d602fe19f6f9233bc8634c411/R/calcCapital.R#L28) calculates the capital/GDP ratio. If GDP is lower, then capital/GDP is higher. If you multiply that with your desired SSP2 GDP, you get a higher capital stock.

**Comment by mleimbach** [comment]
Ok,capital intensity changes. Makes sense.
