### ISSUE TITLE
historical.mif: improve data

### ISSUE THREAD

**Issue by robertpietzcker** [pik-piam/mrremind#411]
It seems that UNFCCC emissions data for the US is missing, but present for EUR, such as:

Emi|GHG
Emi|CO2
Emi|CO2|w/ Bunkers
Emi|GHG|w/ Bunkers

I would have guessed that all Annex I countries need to report this data, so they should be there for the US?

**Comment by fbenke-pik** [comment]
The problem is that we have fixed calculations like

```
  x[, , "Emi|CO2 (Mt CO2/yr)"] <-
    x[, , "Emi|CO2|Agriculture (Mt CO2/yr)"] +
    x[, , "Emi|CO2|Energy (Mt CO2/yr)"] +
    x[, , "Emi|CO2|Industrial Processes (Mt CO2/yr)"] +
    x[, , "Emi|CO2|Land-Use Change (Mt CO2/yr)"] +
    x[, , "Emi|CO2|Waste (Mt CO2/yr)"]
```

and currently they give the result NA if only one of the summands is NA. for USA, `"Emi|CO2|Waste (Mt CO2/yr)"` is NA

@robertpietzcker Is it ok to assume 0 for missing values in order to get results anyways?

**Comment by robertpietzcker** [comment]
@fbenke-pik 
yes, I would say that is reasonable. 
where did you see the NAs?

when I download the data from the UNFCCC, USA also reports the overall Waste emissions (Category 5), only 5c is missing for USA and EUR, but that shouldn't matter as they report the total needed for this sum

[Annual Net emissions_removals(8).xlsx](https://github.com/pik-piam/mrremind/files/12214086/Annual.Net.emissions_removals.8.xlsx)

**Comment by fbenke-pik** [comment]
According to the current mapping `Emi|CO2|Waste`  is the value in Table5 under "Total Waste", which is not a number, but `NO,IE,NA`.

**Comment by robertpietzcker** [comment]
right, we are also looking at CO2, not only GHG.
