### ISSUE TITLE
historical.mif: latest version doesn't seem to have IEA Energy Balances and EUROSTAT data anymore?

### ISSUE THREAD

**Issue by robertpietzcker** [pik-piam/mrremind#442]
I started a run today, and in the historical.mif I cannot find any sources except for the WEOs, the ETP and a few "N/A" entries - no UNFCCC, no EUROSTAT, no IEA Energy balances, ....

![image](https://github.com/pik-piam/mrremind/assets/61154412/d8fe46f6-fbfa-451d-9c1a-e2e79da7d85a)

it would be great if they could be added back :-)

**Comment by fbenke-pik** [comment]
Should be a temporary bug that has been solved already. Can you manually drop the latest historical.mif into your folder?

**Comment by robertpietzcker** [comment]
but I got this historical from cloning a current REMIND version today - so is it really fixed already?

**Comment by fbenke-pik** [comment]
It is fixed in mrremind. For the next steps, please refer to @LaviniaBaumstark

**Comment by robertpietzcker** [comment]
thanks, Falk!

**Comment by LaviniaBaumstark** [comment]
we have new inptu data including historical.mif (6.605) available now
