### ISSUE TITLE
1254ef1 effectively disabled 31_fossil/timeDepGrades and 31_fossil/MOFEX

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#447]
https://github.com/pik-piam/mrremind/blob/9f76aead3973bc531a1ff69b61c4508fe90f3822/R/fullREMIND.R#L161-L164

Maybe it's time to either fix this, or remove the realisations.

**Comment by johanneskoch94** [comment]
Lines were removed in 50653693f07a2aa3ee3b40a78351ca2a312a1a4d.
