### ISSUE TITLE
unused argument from fullVALIDATIONREMIND() is indeed used by madrat

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/mrremind#459]
See [madrat#197](https://github.com/pik-piam/madrat/issues/197).

**Comment by fbenke-pik** [comment]
Not surprised that this eventually came back to bit me in the butt

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
> Not surprised that this eventually came back to bite me in the butt

Well, that did reduce the interface of the package and should [by rights](https://semver.org/) have been a major update rather than a patch.
